// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";

export const ScName        = "faucet";
export const ScDescription = "faucet description";
export const HScName       = new wasmlib.ScHname(0x530abd91);

export const ParamAmount = "amount";
export const ParamOwner  = "owner";

export const ResultMaxTokenAmount   = "maxTokenAmount";
export const ResultMaxTokenRequests = "maxTokenRequests";

export const StateOwner         = "owner";
export const StateTokenRequests = "tokenRequests";

export const FuncDeposit             = "deposit";
export const FuncInit                = "init";
export const FuncRequestToken        = "requestToken";
export const FuncSetOwner            = "setOwner";
export const ViewGetMaxTokenAmount   = "getMaxTokenAmount";
export const ViewGetMaxTokenRequests = "getMaxTokenRequests";

export const HFuncDeposit             = new wasmlib.ScHname(0xbdc9102d);
export const HFuncInit                = new wasmlib.ScHname(0x1f44d644);
export const HFuncRequestToken        = new wasmlib.ScHname(0x9d5cb3df);
export const HFuncSetOwner            = new wasmlib.ScHname(0x2a15fe7b);
export const HViewGetMaxTokenAmount   = new wasmlib.ScHname(0x637679bc);
export const HViewGetMaxTokenRequests = new wasmlib.ScHname(0xed17adcd);
