// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export const IdxParamAmount = 0;
export const IdxParamOwner  = 1;

export const IdxResultMaxTokenAmount   = 2;
export const IdxResultMaxTokenRequests = 3;

export const IdxStateOwner         = 4;
export const IdxStateTokenRequests = 5;

export let keyMap: string[] = [
	sc.ParamAmount,
	sc.ParamOwner,
	sc.ResultMaxTokenAmount,
	sc.ResultMaxTokenRequests,
	sc.StateOwner,
	sc.StateTokenRequests,
];

export let idxMap: wasmlib.Key32[] = new Array(keyMap.length);
