// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export function on_call(index: i32): void {
    return wasmlib.onCall(index);
}

export function on_load(): void {
    let exports = new wasmlib.ScExports();
    exports.addFunc(sc.FuncDeposit,             funcDepositThunk);
    exports.addFunc(sc.FuncInit,                funcInitThunk);
    exports.addFunc(sc.FuncRequestToken,        funcRequestTokenThunk);
    exports.addFunc(sc.FuncSetOwner,            funcSetOwnerThunk);
    exports.addView(sc.ViewGetMaxTokenAmount,   viewGetMaxTokenAmountThunk);
    exports.addView(sc.ViewGetMaxTokenRequests, viewGetMaxTokenRequestsThunk);

    for (let i = 0; i < sc.keyMap.length; i++) {
        sc.idxMap[i] = wasmlib.Key32.fromString(sc.keyMap[i]);
    }
}

function funcDepositThunk(ctx: wasmlib.ScFuncContext): void {
	ctx.log("faucet.funcDeposit");
	let f = new sc.DepositContext();
    f.params.mapID = wasmlib.OBJ_ID_PARAMS;
    f.state.mapID = wasmlib.OBJ_ID_STATE;
	ctx.require(f.params.amount().exists(), "missing mandatory amount");
	sc.funcDeposit(ctx, f);
	ctx.log("faucet.funcDeposit ok");
}

function funcInitThunk(ctx: wasmlib.ScFuncContext): void {
	ctx.log("faucet.funcInit");
	let f = new sc.InitContext();
    f.params.mapID = wasmlib.OBJ_ID_PARAMS;
    f.state.mapID = wasmlib.OBJ_ID_STATE;
	sc.funcInit(ctx, f);
	ctx.log("faucet.funcInit ok");
}

function funcRequestTokenThunk(ctx: wasmlib.ScFuncContext): void {
	ctx.log("faucet.funcRequestToken");
	let f = new sc.RequestTokenContext();
    f.params.mapID = wasmlib.OBJ_ID_PARAMS;
    f.state.mapID = wasmlib.OBJ_ID_STATE;
	ctx.require(f.params.amount().exists(), "missing mandatory amount");
	sc.funcRequestToken(ctx, f);
	ctx.log("faucet.funcRequestToken ok");
}

function funcSetOwnerThunk(ctx: wasmlib.ScFuncContext): void {
	ctx.log("faucet.funcSetOwner");

	// current owner of this smart contract
	let access = ctx.state().getAgentID(wasmlib.Key32.fromString("owner"));
	ctx.require(access.exists(), "access not set: owner");
	ctx.require(ctx.caller().equals(access.value()), "no permission");

	let f = new sc.SetOwnerContext();
    f.params.mapID = wasmlib.OBJ_ID_PARAMS;
    f.state.mapID = wasmlib.OBJ_ID_STATE;
	ctx.require(f.params.owner().exists(), "missing mandatory owner");
	sc.funcSetOwner(ctx, f);
	ctx.log("faucet.funcSetOwner ok");
}

function viewGetMaxTokenAmountThunk(ctx: wasmlib.ScViewContext): void {
	ctx.log("faucet.viewGetMaxTokenAmount");
	let f = new sc.GetMaxTokenAmountContext();
    f.results.mapID = wasmlib.OBJ_ID_RESULTS;
    f.state.mapID = wasmlib.OBJ_ID_STATE;
	sc.viewGetMaxTokenAmount(ctx, f);
	ctx.log("faucet.viewGetMaxTokenAmount ok");
}

function viewGetMaxTokenRequestsThunk(ctx: wasmlib.ScViewContext): void {
	ctx.log("faucet.viewGetMaxTokenRequests");
	let f = new sc.GetMaxTokenRequestsContext();
    f.results.mapID = wasmlib.OBJ_ID_RESULTS;
    f.state.mapID = wasmlib.OBJ_ID_STATE;
	sc.viewGetMaxTokenRequests(ctx, f);
	ctx.log("faucet.viewGetMaxTokenRequests ok");
}
