// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export class MapAgentIDToImmutableAgentState {
	objID: i32;

    constructor(objID: i32) {
        this.objID = objID;
    }

    getAgentState(key: wasmlib.ScAgentID): sc.ImmutableAgentState {
        return new sc.ImmutableAgentState(this.objID, key.getKeyID());
    }
}

export class ImmutablefaucetState extends wasmlib.ScMapID {
    owner(): wasmlib.ScImmutableAgentID {
		return new wasmlib.ScImmutableAgentID(this.mapID, sc.idxMap[sc.IdxStateOwner]);
	}

    tokenRequests(): sc.MapAgentIDToImmutableAgentState {
		let mapID = wasmlib.getObjectID(this.mapID, sc.idxMap[sc.IdxStateTokenRequests], wasmlib.TYPE_MAP);
		return new sc.MapAgentIDToImmutableAgentState(mapID);
	}
}

export class MapAgentIDToMutableAgentState {
	objID: i32;

    constructor(objID: i32) {
        this.objID = objID;
    }

    clear(): void {
        wasmlib.clear(this.objID);
    }

    getAgentState(key: wasmlib.ScAgentID): sc.MutableAgentState {
        return new sc.MutableAgentState(this.objID, key.getKeyID());
    }
}

export class MutablefaucetState extends wasmlib.ScMapID {
    owner(): wasmlib.ScMutableAgentID {
		return new wasmlib.ScMutableAgentID(this.mapID, sc.idxMap[sc.IdxStateOwner]);
	}

    tokenRequests(): sc.MapAgentIDToMutableAgentState {
		let mapID = wasmlib.getObjectID(this.mapID, sc.idxMap[sc.IdxStateTokenRequests], wasmlib.TYPE_MAP);
		return new sc.MapAgentIDToMutableAgentState(mapID);
	}
}
